Repository liferay/alloy-editor, pull requests merged in 2019-05, with the labels that each got.

#1259 fix: improve drag handler visibility on IE (#1255)
  src/plugins/dragresize_ie11.js
Labels: 1.5.x, enhancement

#1262 chore: fix formatting
  src/plugins/dragresize_ie11.js
Labels: 2.0.x, chore

#1264 feat: add check to prevent publishing without annotated tag
  package.json
  scripts/publish/check.js
Labels: feature

#1271 chore: Prepare for release v2.0.5
  CHANGELOG.md
  package.json
Labels: 2.0.x
